default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  primary: &primary_production
    <<: *default
    database: blog_production
    username: blog
    password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: blog_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: blog_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: blog_production_cable
    migrations_paths: db/cable_migrate
